"""create venues table

Revision ID: 7fc92cf45d90
Revises: 82f3fcf1bc7c
Create Date: 2026-10-03 07:41:33.218265
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '7fc92cf45d90'
down_revision: str | None = '82f3fcf1bc7c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venues',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_venues_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_venues'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venues')
    # ### end Alembic commands ###
